# Generated by Django 4.1.3 on 2023-01-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1999-9-12'),
            preserve_default=False,
        ),
    ]
